name: Ruff Lint

on:
  workflow_dispatch:

  # Come back to after
  #push:
   # branches: [ main ]

  pull_request:
    types: [ opened, synchronize, reopened ]


jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:

