name: Validate JSON Syntax
on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  validate-json:
    strategy:
      fail-fast: true
      matrix:
        files: [ "src/google_apis_forms/attendance-form_v0.json" ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Verify JSON Syntax
        shell: bash
        run: |
            jq empty ${{ matrix.files }}
